<?php

use Egits\Integration\Block\Brands;

$blockobj = $block->getLayout()->createBlock(Brands::class);

$brands = $blockobj->getDataForPHTML();

//var_dump($category);
?>

<script type="text/javascript">
    require(['jquery', 'label'], function($) {
        $('.top-brandSlider').owlCarousel({
            loop: true,
            dots: false,
            autoPlay: 2000,
            responsive: {
                0: {
                    autoWidth: true,
                    margin: 10
                },
                768: {
                    items: 4
                },
                860: {
                    items: 5
                },
                992: {
                    items: 4
                },
                1300: {
                    items: 5
                },
                1500: {
                    items: 6
                }
            }
        })
        // Your custom JavaScript code here, if needed
        // Example: $('.top-category-slider').owlCarousel();
    });
</script>

<section class="top-brands-section">
    <div class="page-main">
        <div class="content-heading">
            <h2 class="title">Top brands</h2>
        </div>
        <ul class="owl-carousel owl-theme top-brands-slider top-brandSlider owl-loaded owl-drag">
            <?php foreach ($brands as $brand) : ?>
                <li class="top-brands-list">
                    <a href="#">
                        <figure class="top-brands-image" style="background-image: url('<?php echo $brand['image_url']; ?>');"> </figure>
                        <h4><?php echo $brand['brand_name']; ?></h4>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</section>