<?php
use Egits\Integration\Block\Category;

$blockobj = $block->getLayout()->createBlock(Category::class);

$test = $blockobj->getDataForPHTML();

//var_dump($test);
?>

<script type="text/javascript">
require(['wktestrequire'], function() {
    // Your custom JavaScript code here, if needed
    // Example: $('.top-category-slider').owlCarousel();
});
</script>

<section class="top-category-section">
    <div class="page-main">
        <div class="content-heading">
            <h2 class="title">Top Categories</h2>
        </div>
        <ul class="owl-theme top-category-slider">
            <?php foreach ($test as $item): ?>
            <li class="top-category-list">
                <a href="#">
                    <figure class="top-category-image" style="background-image: url('<?php echo $item['image']; ?>');">
                    </figure>
                    <h4><?php echo $item['url_key']; ?></h4>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</section>

<!--<section class="top-category-section">-->
<!--    <div class="page-main">-->
<!--        <div class="content-heading">-->
<!--            <h2 class="title">Top Categories</h2>-->
<!--        </div>-->
<!--        <ul class="owl-theme top-category-slider">-->
<!--            <li class="top-category-list">-->
<!--                <a href="#">-->
<!--                    <figure class="top-category-image" style="background-image: url('images/top-category-image/category1.jpg');"> </figure>-->
<!--                    <h4>Kurta</h4>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="top-category-list">-->
<!--                <a href="#">-->
<!--                    <figure class="top-category-image" style="background-image: url('images/top-category-image/category2.jpg');"> </figure>-->
<!--                    <h4>Hand Bags</h4>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="top-category-list">-->
<!--                <a href="#">-->
<!--                    <figure class="top-category-image" style="background-image: url('images/top-category-image/category3.jpg');"> </figure>-->
<!--                    <h4>Watches</h4>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="top-category-list">-->
<!--                <a href="#">-->
<!--                    <figure class="top-category-image" style="background-image: url('images/top-category-image/category4.jpg');"> </figure>-->
<!--                    <h4>Earphones</h4>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="top-category-list">-->
<!--                <a href="#">-->
<!--                    <figure class="top-category-image" style="background-image: url('images/top-category-image/category5.jpg');"> </figure>-->
<!--                    <h4>T-Shirt</h4>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="top-category-list">-->
<!--                <a href="#">-->
<!--                    <figure class="top-category-image" style="background-image: url('images/top-category-image/category6.jpg');"> </figure>-->
<!--                    <h4>Shoes</h4>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="top-category-list">-->
<!--                <a href="#">-->
<!--                    <figure class="top-category-image" style="background-image: url('images/top-category-image/category7.jpg');"> </figure>-->
<!--                    <h4>jeans</h4>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="top-category-list">-->
<!--                <a href="#">-->
<!--                    <figure class="top-category-image" style="background-image: url('images/top-category-image/category8.jpg');"> </figure>-->
<!--                    <h4>tops</h4>-->
<!--                </a>-->
<!--            </li>-->
<!--            <li class="top-category-list">-->
<!--                <a href="#">-->
<!--                    <figure class="top-category-image" style="background-image: url('images/top-category-image/category9.jpg');"> </figure>-->
<!--                    <h4>sarees</h4>-->
<!--                </a>-->
<!--            </li>-->
<!--        </ul>-->
<!--    </div>-->
<!--</section>-->