<?php
$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
$currentUrl = $block->getCurrentUrl();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 home <?php if ($currentUrl == '/') : ?>active<?php endif; ?>"><a href="<?php echo $storeManager->getStore()->getBaseUrl(); ?>" title="<?php echo __('Home') ?>" class="level-top"><span><?php echo __('Home') ?></span></a></li>

        <!-- <li class="level0 <?php //if ($currentUrl == '/testlink') : 
                                ?>active<?php //endif; 
                                        ?>"><a href="<?php //echo $storeManager->getStore()->getBaseUrl() . 'testlink'; 
                                                        ?>" title="<?php // echo __('Test Link is this') 
                                                                    ?>" class="level-top"><span>Test Link</span></a></li> -->
        <?php echo $_menu; ?>
    </ul>
</nav>